OnlineBookClub.WEB/Controllers/EventController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineBookClub.WEB.Models;
using OnlineBookClub.WEB.Models.DB.Const;
using OnlineBookClub.WEB.Models.DB.Event;
using OnlineBookClub.WEB.Models.Identity;
using OnlineBookClub.WEB.ViewModels;
using OpenLibraryNET;
using OpenLibraryNET.Data;
using OpenLibraryNET.Utility;

namespace OnlineBookClub.WEB.Controllers
{
    public class EventController : Controller
    {
        private OnlineBookClubContext _context;
        private readonly UserManager<AppUser> _userManager;

        public EventController(OnlineBookClubContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            Event_IndexVM model = new Event_IndexVM()
            {
                Events = _context.Events.Include(x => x.EventSubjects).Include(x => x.Location).ToList(),
            };

            return View(model);
        }

        public async Task<IActionResult> Details(int id)
        {
            EventDetailsVM model = new EventDetailsVM()
            {
                Event = _context.Events.Where(x => x.Id == id).Include(x => x.EventSubjects).Include(x => x.Location).Include(x => x.EventRatings).Include(x => x.School).Include(x => x.CREATED_USER_).FirstOrDefault()!,
            };

            OpenLibraryClient olClinet = new OpenLibraryClient();

            try
            {
                OLEdition oLEdition = await olClinet.GetEditionAsync(model.Event.ISBN, OpenLibraryNET.Utility.BookIdType.ISBN);
                model.BookName = oLEdition.Data.Title;
                model.BookDescription = oLEdition.Data.Description;
                byte[] coverSmall = await olClinet.Image.GetCoverAsync(CoverIdType.ISBN, model.Event.ISBN, ImageSize.Large);

                model.BookImage = string.Format("data:image/png;base64,{0}", Convert.ToBase64String(coverSmall));

            }
            catch (Exception)
            {
                return View("Error");
                throw;
            }

            //switch (eventModel.ISBN)
            //{
            //    case "1ASDF":
            //        ViewBag.BookName = "Nutuk";
            //        break;

            //    case "DSFDSF":
            //        ViewBag.BookName = "Ateşten Gömlek";
            //        break;

            //    default:
            //        ViewBag.BookName = eventModel.ISBN;
            //        break;
            //}

            return View(model);
        }

        public async Task<IActionResult> JoinEvent(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction(nameof(HomeController.SignUp));
            }

            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name);

            if (_context.EventRatings.FirstOrDefault(x => x.UserId == currentUser.Id) == null)
            {
                return RedirectToAction(nameof(EventController.Details), new { id = id });
            }

            _context.EventRatings.Add(new EventRating()
            {
                CREATED_DATE = DateTime.UtcNow,
                EventId = id,
                UserId = currentUser.Id,
                Rating = 1
            }) ;

            _context.SaveChanges();

            return RedirectToAction(nameof(EventController.Details), new { id = id });
        }

         public IActionResult Guides()
        {
            return View();
        }
    }
}

OnlineBookClub.WEB/Controllers/UserController.cs
using AspNetCoreIdentityApp.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;
using OnlineBookClub.WEB.Enums;
using OnlineBookClub.WEB.Models;
using OnlineBookClub.WEB.Models.Identity;
using OnlineBookClub.WEB.ViewModels.Auth;
using System.Security.Claims;

namespace OnlineBookClub.WEB.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly IFileProvider _fileProvider;
        private readonly OnlineBookClubContext _context;

        public UserController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, IFileProvider fileProvider, OnlineBookClubContext context)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _fileProvider = fileProvider;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name);
            UserVM userVM = new UserVM
            {
                UserName = currentUser.UserName,
                Email = currentUser.Email,
                PhoneNumber = currentUser.PhoneNumber,
                Department = _context.Departments.FirstOrDefault(x => x.Id == currentUser.DepartmentId),
                Firstname = currentUser.Firstname,
                Lastname = currentUser.Lastname,
                Gender = currentUser.Gender,
                Level = _context.Levels.FirstOrDefault(x => x.LevelId == currentUser.LevelId),
                Point = currentUser.Point,
                School = _context.Schools.FirstOrDefault(x => x.Id == currentUser.SchoolId),
                SchoolNo = currentUser.SchoolNo,
                ProfilePicture = string.IsNullOrEmpty(currentUser.ProfilePicture) ? "DefaultUserPicture.jpg" : currentUser.ProfilePicture
            };
            return View(userVM);
        }

        public IActionResult PasswordChange()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeVM request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name);
            var checkOldPassword = _userManager.CheckPasswordAsync(currentUser, request.PasswordOld).Result;

            if (!checkOldPassword)
            {
                ModelState.AddModelError(string.Empty, "Eski şifreniz yanlış!");
                return View();
            }

            var result = await _userManager.ChangePasswordAsync(currentUser, request.PasswordOld, request.PasswordNew);

            if (!result.Succeeded)
            {
                ModelState.AddModelErrorList(result.Errors);
                return View();
            }

            await _userManager.UpdateSecurityStampAsync(currentUser);
            await _signInManager.SignOutAsync();
            await _signInManager.PasswordSignInAsync(currentUser, request.PasswordNew, true, false);

            TempData["SuccessMessage"] = "Şifre başarıyla değişti.";

            return View();
        }

        public async Task<IActionResult> UserEdit()
        {
            ViewBag.genderList = new SelectList(Enum.GetNames(typeof(Gender)));
            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name);
            UserEditVM model = new UserEditVM()
            {
                UserName = currentUser.UserName,
                Email = currentUser.Email,
                Phone = currentUser.PhoneNumber,
                Firstname = currentUser.Firstname!,
                Lastname = currentUser.Lastname!,
                SchoolNo = currentUser.SchoolNo!
            };

			UserVM userVM = new UserVM
			{
				UserName = currentUser.UserName,
				Email = currentUser.Email,
				PhoneNumber = currentUser.PhoneNumber,
				Department = _context.Departments.FirstOrDefault(x => x.Id == currentUser.DepartmentId),
				Firstname = currentUser.Firstname,
				Lastname = currentUser.Lastname,
				Gender = currentUser.Gender,
				Level = _context.Levels.FirstOrDefault(x => x.LevelId == currentUser.LevelId),
				Point = currentUser.Point,
				School = _context.Schools.FirstOrDefault(x => x.Id == currentUser.SchoolId),
				SchoolNo = currentUser.SchoolNo,
				ProfilePicture = string.IsNullOrEmpty(currentUser.ProfilePicture) ? "DefaultUserPicture.jpg" : currentUser.ProfilePicture
			};

            ViewBag.UserVM = userVM;

			return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserEditVM request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name);
            currentUser.UserName = request.UserName;
            currentUser.Email = request.Email;
            currentUser.PhoneNumber = request.Phone;
            currentUser.Firstname = request.Firstname;
            currentUser.Lastname = request.Lastname;    
            currentUser.SchoolNo = request.SchoolNo;

            if (request.ProfilePicture != null && request.ProfilePicture.Length > 0)
            {
                var wwwrootFolder = _fileProvider.GetDirectoryContents("wwwroot");
                string randomFileName = $"{Guid.NewGuid().ToString()}{Path.GetExtension(request.ProfilePicture.FileName)}";

                string userpicturesPath = wwwrootFolder.First(x => x.Name == "img").PhysicalPath + "\\userpictures";

                var newPicturePath = Path.Combine(userpicturesPath, randomFileName);

                using var stream = new FileStream(newPicturePath, FileMode.Create);
                await request.ProfilePicture.CopyToAsync(stream);

                currentUser.ProfilePicture = randomFileName;
            }

            var result = await _userManager.UpdateAsync(currentUser);

            if (!result.Succeeded)
            {
                ModelState.AddModelErrorList(result.Errors);
                return View();
            }

            await _userManager.UpdateSecurityStampAsync(currentUser);
            await _signInManager.SignOutAsync();
            await _signInManager.SignInAsync(currentUser, true);

            TempData["SuccessMessage"] = "Your info are successfully changed.";

            UserEditVM model = new UserEditVM()
            {
                UserName = currentUser.UserName,
                Email = currentUser.Email,
                Phone = currentUser.PhoneNumber,
                Firstname = currentUser.Firstname!,
                Lastname = currentUser.Lastname!,
                SchoolNo = currentUser.SchoolNo!
            };

            return View(model);
        }

        public async Task<IActionResult> LogOut(string returnurl)
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Claims()
        {
            var userClaimList = User.Claims.Select(x => new ClaimVM()
            {
                Issuer = x.Issuer,
                Type = x.Type,
                Value = x.Value
            }).ToList();

            return View(userClaimList);
        }

        [Authorize(Policy = "SchoolPage")]
        public IActionResult SchoolPage()
        {
            return View();
        }

        public async Task<IActionResult> AccessDenied(string ReturnUrl)
        {
            string message = string.Empty;

            message = "You are not have permission for enter this page!";
            ViewBag.message = message;
            return View();
        }
    }
}

OnlineBookClub.WEB/Views/Shared/_Footer.cshtml
<footer>
    <div class="footer-content">
        <div class="footer-logo">
            <h1 class="footer-logo-text">LOGO</h1>
            <p class="footer-logo-desc">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque delectus
                magni temporibus aliquam, voluptate libero molestias consectetur a omnis ipsum.
            </p>
        </div>
        <div class="footer-urls">
            <h1 class="footer-urls-header bold mb-3">
                <span style="color: red; font-weight: default;">|</span>
                LİNKLER
            </h1>
            <a href="/Home/Index"><i class="fa-solid fa-chevron-right color:red;"></i>Ana Sayfa</a>
            <a href="/Home/Index"><i class="fa-solid fa-chevron-right color:red;"></i>Kitap Bul</a>
            <a href="/Home/Index"><i class="fa-solid fa-chevron-right color:red;"></i>Takvim</a>
            <a href="/Home/Index"><i class="fa-solid fa-chevron-right color:red;"></i>Hakkında</a>
            <a href="/Home/Index"><i class="fa-solid fa-chevron-right color:red;"></i>İletişim</a>
        </div>
        <div class="footer-follow">
            <h1 class="footer-follow-header bold">
                <span style="color: red; font-weight: default;">|</span> TAKİP ET
            </h1>
            <p class="footer-follow-desc mt-3">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque
                delectus
                magni temporibus aliquam, voluptate libero molestias consectetur a omnis ipsum.
            </p>
        </div>
        <div class="footer-search">
            <h1 class="footer-search-header bold">
                <span style="color: red; font-weight: default;">|</span> ARAMA
            </h1>
            <p class="footer-search-desc mt-3">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Itaque
                delectus
                magni temporibus aliquam, voluptate libero molestias consectetur a omnis ipsum.
            </p>
            <div class="footer-search-area">
                <textarea placeholder="Arama" name="search" id="search" cols="30" rows="10"></textarea>
                <p class="search-button">Ara</p>
            </div>
        </div>
    </div>
    <div class="footer-end">
        <hr class="footer-hr">
        <p class="mt-2 mb-2">&copy; Copyright <span class="bold">Book.</span> All Rights Reserved</p>
    </div>
</footer>

OnlineBookClub.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineBookClub.WEB</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/OnlineBookClub.WEB.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet" />
    <!-- Vendor CSS Files -->
    <!-- <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet" /> -->
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet" />
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet" />
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet" />
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


    @* Add Custom Css File Area *@
    <link rel="stylesheet" href="~/css/loginAndSignUp.css">
    <link rel="stylesheet" href="~/css/profile.css">
    <link rel="stylesheet" href="~/css/staticStyle.css">
    @* Add Custom Css File Area *@
</head>

<body>

    <!-- ======= Header ======= -->
    <partial name="_Navbar" />
    <!-- End Header -->

    <div>
        <main role="main" class="py-4 d-block">
            @RenderBody()
        </main>
    </div>

    <!-- ======= Footer ======= -->
    <partial name="_Footer" />
    <!-- End Footer -->


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

OnlineBookClub.WEB/Views/Shared/_LayoutBlank.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineBookClub.WEB</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/OnlineBookClub.WEB.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet" />

    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


    @* Add Custom Css File Area *@
    <link rel="stylesheet" href="~/css/LoginAndSignupStyle.css">
    @* Add Custom Css File Area *@
</head>

<body>

    @RenderBody()


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

OnlineBookClub.WEB/Views/Shared/_Navbar.cshtml
@using System.Security.Claims

<nav>
    <div class="Nav-Logo">
        <a asp-controller="Home" asp-action="Index"><p>LOGO</p></a>
    </div>

    <ul>
        <li><a href="">Kitap Bul</a></li>
        <li><a href="">Hakkında</a></li>
        <li><a href="">İletişim</a></li>
        <li><a asp-area="" asp-controller="Home" asp-action="Calendar">Takvim</a></li>
        <li><a asp-area="" asp-controller="Event" asp-action="Index">Etkinlikler</a></li>
        <li><a asp-area="" asp-controller="Home" asp-action="Users">Kullanıcılar</a></li>

        @if (User.Identity!.IsAuthenticated)
        {
            <li>
                <div class="dropdown">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        @{
                            string userpp = @User.Claims.FirstOrDefault(x => x.Type == "ProfilePicture") != null ? User.Claims.First(x => x.Type == "ProfilePicture").Value : "DefaultUserPicture.jpg";
                        }
                        <img src="~/img/userpictures/@userpp" alt="mdo" width="32" height="32" class="rounded-circle" style="object-fit: cover;">
                        @User.Identity.Name
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Profil</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="User" asp-action="PasswordChange">Şifreni Değiştir</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="User" asp-action="UserEdit">Ayarlar</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Claims">Claims</a></li>
                        @if (User.HasClaim(ClaimTypes.Role, "Admin"))
                        {
                            <li><a asp-area="Admin" asp-controller="Home" asp-action="Index" class="dropdown-item">Admin Sayfası</a></li>
                        }
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item text-danger" asp-area="" asp-controller="User" asp-action="LogOut" asp-route-returnurl="/Home/Index">Çıkış Yap</a></li>
                    </ul>
                </div>
            </li>
        }
        else
        {
            <li>
                <a asp-controller="Home" asp-action="LogIn">
                    <a asp-controller="Home" asp-action="LogIn" class="Nav-Button">Giriş Yap</a>
                </a>

                <a asp-controller="Home" asp-action="SignUp">
                    <a asp-controller="Home" asp-action="SignUp" class="Nav-Button">Kayıt Ol</a>
                </a>
            </li>
        }
    </ul>
</nav>

OnlineBookClub.WEB/Views/Shared/_ProfileSidebarPartial.cshtml
@using System.Security.Claims
@model UserVM

@{
    var userPicture = User.Claims.FirstOrDefault(x => x.Type == "ProfilePicture") != null ? User.Claims.FirstOrDefault(x => x.Type == "ProfilePicture").Value : "DefaultUserPicture.jpg";
}

<div class="Sidebar">
    <div class="Sidebar-Area">
        <div class="Sidebar-Up">
            <div class="Profile">
                <img src="~/img/userpictures/@userPicture" style="object-fit: cover;" alt="">
                <div class="d-flex gap-2">
                    <p class="mt-5">@Model.Firstname</p>
                    <p class="mt-5">@Model.Lastname</p>
                </div>
            </div>

            <div class="SidebarUpLinks">
                <ul>
                    <li><a href="profile.html">Genel Bakış</a></li>
                    <li><a href="readedbook.html">Okuduğum Kitaplar</a></li>
                    <li><a href="wantreadbook.html">Okumak İstediğim Kitaplar</a></li>
                </ul>
            </div>
        </div>



        <div class="Sidebar-Down">
            <ul>
                <li>
                    <h4>Telefon</h4>
                    <p>@Model.PhoneNumber</p>
                    <div class="Underline"></div>
                </li>

                <li>
                    <h4>E-Posta</h4>
                    <p>@Model.Email</p>
                    <div class="Underline"></div>
                </li>

                <li>
                    <h4>Okul Numarası</h4>
                    <p>@Model.SchoolNo</p>
                    <div class="Underline"></div>
                </li>
            </ul>

            <div class="Siderbar-Footer">
                <ul>
                    <li><a href="settings.html">Profilimi Düzenle</a></li>
                    <li><a href="#">Oturumu Kapat</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>